// Per-check "Learn More" targets on Optia's own docs site (site/docs in this
// repo, published via GitHub Pages). Keyed by check id — titles can be dynamic
// (e.g. the word-count check interpolates its threshold), ids are stable.
// The pages are generated by scripts/build-docs-site.mjs; slugs must stay in
// sync with the PAGES data there.
const BASE_URL = "https://pmdevsolutions.github.io/Optia/docs";

const CHECK_URLS: Record<string, string> = {
  "title-present": `${BASE_URL}/meta-seo/page-title.html`,
  "title-length": `${BASE_URL}/meta-seo/page-title.html`,
  "title-keyword": `${BASE_URL}/meta-seo/page-title.html`,
  "meta-description-present": `${BASE_URL}/meta-seo/meta-description.html`,
  "meta-description-length": `${BASE_URL}/meta-seo/meta-description.html`,
  "meta-description-keyword": `${BASE_URL}/meta-seo/meta-description.html`,
  "keyword-url": `${BASE_URL}/meta-seo/keyword-in-url.html`,
  "og-tags": `${BASE_URL}/meta-seo/open-graph.html`,
  "og-image": `${BASE_URL}/meta-seo/open-graph.html`,
  "h1-present": `${BASE_URL}/content/h1-heading.html`,
  "h1-keyword": `${BASE_URL}/content/h1-heading.html`,
  "heading-hierarchy": `${BASE_URL}/content/heading-hierarchy.html`,
  "h2-keyword": `${BASE_URL}/content/h2-headings.html`,
  "keyword-density": `${BASE_URL}/content/keyword-density.html`,
  "keyword-intro": `${BASE_URL}/content/introduction.html`,
  "word-count": `${BASE_URL}/content/content-length.html`,
  "internal-links": `${BASE_URL}/links/internal-links.html`,
  "outbound-links": `${BASE_URL}/links/outbound-links.html`,
  "images-alt": `${BASE_URL}/images/alt-text.html`,
  "next-gen-images": `${BASE_URL}/images/next-gen-formats.html`,
  "image-file-size": `${BASE_URL}/images/image-file-size.html`,
  canonical: `${BASE_URL}/technical/canonical-url.html`,
  lang: `${BASE_URL}/technical/language-attribute.html`,
  "schema-markup": `${BASE_URL}/technical/schema-markup.html`,
  "code-minification": `${BASE_URL}/technical/code-minification.html`,
};

export function getLearnMoreUrl(checkId: string): string {
  return CHECK_URLS[checkId] || `${BASE_URL}/index.html`;
}
